[package]
name = "sink"
version = "1.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-web-static-files = "4.0.1"
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
deadpool-sqlite = "0.6.0"
env_logger = "0.10.0"
libc = "0.2.149"
log = "0.4.20"
regex = "1.10.2"
rusqlite = { version = "0.29.0", features = ["bundled", "functions"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
static-files = "0.2.3"
xml-rs = "0.8.19"

[build-dependencies]
cc = "1.0.83"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
strip = true
