[package]
name = "sink"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
actix-web-static-files = "4.0.1"
anyhow = "1.0.69"
chrono = "0.4.23"
clap = { version = "4.1.6", features = ["derive"] }
csv = "1.2.0"
deadpool-sqlite = "0.5.0"
env_logger = "0.10.0"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.17"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
static-files = "0.2.3"
xml-rs = "0.8.4"

[build-dependencies]
static-files = "0.2.3"
