[package]
name = "sink"
version = "1.3.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.7.1"
clap = { version = "4.4.8", features = ["derive"] }
deadpool = "0.10.0"
libc = "0.2.150"
regex = "1.10.2"
rusqlite = { version = "0.30.0", features = ["bundled", "functions"] }
rust-embed = { version = "8.0.0", features = ["mime-guess"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
cc = "1.0.83"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
strip = true
