[package]
name = "sink"
version = "1.6.8"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive"] }
deadpool = "0.11.2"
libc = "0.2.154"
regex = "1.10.4"
rusqlite = { version = "0.31.0", features = ["bundled", "functions"] }
rust-embed = { version = "8.3.0", features = ["mime-guess"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
cc = "1.0.96"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
