[package]
name = "sink"
version = "1.1.5"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
deadpool-sqlite = "0.6.0"
libc = "0.2.149"
regex = "1.10.2"
rusqlite = { version = "0.29.0", features = ["bundled", "functions"] }
rust-embed = { version = "8.0.0", features = ["mime-guess"] }
quick-xml = "0.31.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["full"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[build-dependencies]
cc = "1.0.83"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
strip = true
