[package]
name = "sink"
version = "1.7.3"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive"] }
const_format = "0.2.32"
deadpool = "0.12.1"
libc = "0.2.155"
regex = "1.10.4"
rusqlite = { version = "0.31.0", features = ["bundled", "functions"] }
rust-embed = { version = "8.4.0", features = ["include-exclude", "mime-guess"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
cc = "1.0.98"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
