[package]
name = "sink"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
actix-web-static-files = "4.0.1"
anyhow = "1.0.70"
chrono = { version = "0.4.24", features = ["unstable-locales"] }
chrono-tz = "0.8.2"
clap = { version = "4.2.5", features = ["derive"] }
deadpool = "0.9.5"
deadpool-sqlite = "0.5.0"
env_logger = "0.10.0"
libc = "0.2.142"
log = "0.4.17"
md5 = "0.7.0"
num_cpus = "1.15.0"
rquickjs = { version = "0.1.7", features = ["bindgen", "loader", "macro", "parallel", "tokio"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
static-files = "0.2.3"
tokio = { version = "1.28.0", features = ["rt-multi-thread"] }
xml-rs = "0.8.4"

[build-dependencies]
cc = "1.0.79"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
strip = true
