[package]
name = "sink"
version = "1.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
axum = "0.7.4"
clap = { version = "4.5.1", features = ["derive"] }
deadpool = "0.10.0"
libc = "0.2.153"
regex = "1.10.3"
rusqlite = { version = "0.31.0", features = ["bundled", "functions"] }
rust-embed = { version = "8.2.0", features = ["mime-guess"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["full"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
cc = "1.0.83"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
