[package]
name = "sink"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
actix-web-static-files = "4.0.1"
anyhow = "1.0.70"
chrono = "0.4.24"
clap = { version = "4.1.11", features = ["derive"] }
csv = "1.2.1"
deadpool-sqlite = "0.5.0"
env_logger = "0.10.0"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
libc = "0.2.140"
log = "0.4.17"
rquickjs = "0.1.7"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
static-files = "0.2.3"
xml-rs = "0.8.4"

[build-dependencies]
cc = "1.0.79"
static-files = "0.2.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
